# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Henry Cheung
email: henryc@mit.edu
description: >- # this means to ignore newlines until "baseurl:"
  Check out the things I've made on this site. Contact me if there's anything
  cool you want to talk about.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cheunghenry.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  henryc804
#twitter_username: jekyllrb

repository: "henryc/bootstrap-4-github-pages"

# Build settings
markdown: kramdown
incremental: false  # Only re-builds parts of site that have changed,
                    #   experimental so may break site...use at own risk
profile: true   # creates a Liquid profile in order to identify bottlenecks
strict_front_matter: true   # causes build fail if YAML front matter is wrong
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
  - README.md
